resolver: lts-5.18
compiler: ghcjs-0.2.0.20160414_ghc-7.10.3
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.20160414_ghc-7.10.3:
        url: https://s3.amazonaws.com/ghcjs/ghcjs-0.2.0.20160414_ghc-7.10.3.tar.gz
        sha1: 6d6f307503be9e94e0c96ef1308c7cf224d06be3

extra-deps:
- ghcjs-dom-0.2.3.1

packages:
  - location:
      git: https://github.com/grumply/ef.git
      commit: c3dbe69c1e61461fe94905136b7e8c6fad0a4a26
    subdirs:
      - ef-core
      - ef-base
  - '.'
